// ==================================================================================
// SHREE RADHE KRISHNA DIGITAL SERVICE – Business Knowledge & Catalog
// Integrated into JARVIS Operating System
// NOTE: Adheres strictly to Section 7 Contact Rule:
// Public contact method: EMAIL ONLY (khushidigitalseva11@gmail.com).
// No public phone number or WhatsApp buttons exposed.
// ==================================================================================

import { DigitalService } from '../types/digitalSeva';
import { BusinessKnowledgeItem, BrandGuidelines } from '../types/jarvis';

export const BUSINESS_INFO = {
  name: 'SHREE RADHE KRISHNA DIGITAL SERVICE',
  name_gu: 'શ્રી રાધે કૃષ્ણ ડિજિટલ સેવા',
  tagline_gu: 'તમારી ડિજિટલ સેવા, એક જ સ્થળે',
  tagline_en: 'Your Complete Digital Service, Under One Roof',
  email: 'khushidigitalseva11@gmail.com', // Public Email Only
  address: 'Rudra Complex, Timberwa Road, Sadhli, Taluka Shinor, District Vadodara, Gujarat, India.',
  workingHours: 'Monday–Saturday: 9:00 AM–7:00 PM (Sunday Closed)',
  pvcDelivery: 'All India PVC Smart Card Home Delivery Available',
  domain: 'srkdigital.online',
};

export const BRAND_GUIDELINES: BrandGuidelines = {
  brand_name: 'SHREE RADHE KRISHNA DIGITAL SERVICE',
  brand_name_gu: 'શ્રી રાધે કૃષ્ણ ડિજિટલ સેવા',
  tagline_gu: 'સરળ, ઝડપી અને વિશ્વાસપાત્ર સરકારી યોજના સહાય',
  tagline_en: 'Trusted Citizen & Digital Service Center',
  primary_color: '#3B82F6', // Vibrant Royal Blue
  secondary_color: '#8B5CF6', // Purple Accent
  gold_accent: '#F59E0B', // Saffron / Gold
  dark_bg: '#090D16', // Deep Obsidian Dark
  public_email: 'khushidigitalseva11@gmail.com',
  font_gujarati: 'Noto Sans Gujarati, Shruti, sans-serif',
  font_english: 'Inter, system-ui, sans-serif',
  disclaimer_gu: 'નોંધ: અમે એક સ્વતંત્ર ડિજિટલ સેવા કેન્દ્ર છીએ. સરકારી પોર્ટલ પર અરજી કરવામાં નાગરિકોને સહાય કરીએ છીએ.',
  disclaimer_en: 'Disclaimer: We are an independent digital assistance center providing citizen facilitation services on official portals.',
  watermark_enabled: true,
  watermark_position: 'Bottom Right',
};

export const INITIAL_SERVICES: DigitalService[] = [
  {
    id: 'srv-1',
    service_code: 'PAN',
    name: 'New PAN Card',
    name_gu: 'નવું PAN Card',
    price: 250,
    category: 'PAN Card',
    description: 'નવું PAN Card બનાવવા માટે ઓનલાઈન અરજી સહાય. 18 વર્ષથી વધુ ઉંમરના તમામ ભારતીય નાગરિકો માટે.',
    instructions: 'ઓરિજિનલ આધાર કાર્ડ અને સફેદ બેકગ્રાઉન્ડ વાળો પાસપોર્ટ ફોટો અને સફેદ કાગળ પર સહી અપલોડ કરો.',
    active: true,
    display_order: 1,
    required_documents: [
      { id: 'doc-pan-1', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card (Front & Back)', doc_name_gu: 'આધાર કાર્ડ (આગળ અને પાછળ)', is_mandatory: true },
      { id: 'doc-pan-2', doc_code: 'PHOTO', doc_name: 'Passport Size Photo', doc_name_gu: 'પાસપોર્ટ સાઇઝ ફોટો', is_mandatory: true },
      { id: 'doc-pan-3', doc_code: 'SIGN', doc_name: 'Signature on White Paper', doc_name_gu: 'સફેદ કાગળ પર સહી', is_mandatory: true },
    ],
    form_fields: [
      { id: 'f-1', field_name: 'app_name', label: 'Full Name as per Aadhaar', label_gu: 'આધાર કાર્ડ મુજબ પૂરું નામ', field_type: 'text', is_required: true, display_order: 1 },
      { id: 'f-2', field_name: 'father_name', label: "Father's Full Name", label_gu: 'પિતાનું પૂરું નામ', field_type: 'text', is_required: true, display_order: 2 },
      { id: 'f-3', field_name: 'dob', label: 'Date of Birth', label_gu: 'જન્મ તારીખ', field_type: 'date', is_required: true, display_order: 3 },
    ],
  },
  {
    id: 'srv-2',
    service_code: 'PANC',
    name: 'PAN Card Correction',
    name_gu: 'PAN Card સુધારો',
    price: 250,
    category: 'PAN Card',
    description: 'PAN Card માં નામ, પિતાનું નામ, જન્મ તારીખ, ફોટો અથવા સહી સુધારા માટે સંપૂર્ણ ઓનલાઈન સહાય.',
    instructions: 'હાલનું પાન કાર્ડ અને જે માહિતી સુધારવી હોય તેનો માન્ય સરકારી પુરાવો અપલોડ કરવો.',
    active: true,
    display_order: 2,
    required_documents: [
      { id: 'doc-panc-1', doc_code: 'EXISTING_PAN', doc_name: 'Existing PAN Card Copy', doc_name_gu: 'હાલનું PAN Card', is_mandatory: true },
      { id: 'doc-panc-2', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card', doc_name_gu: 'આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-panc-3', doc_code: 'PROOF', doc_name: 'Proof of Correction (LC/Marksheet)', doc_name_gu: 'સુધારા અંગેનો પુરાવો (LC/માર્કશીટ)', is_mandatory: true },
    ],
  },
  {
    id: 'srv-3',
    service_code: 'ENIR',
    name: 'e-Nirman Card',
    name_gu: 'ઈ-નિર્માણ કાર્ડ',
    price: 150,
    category: 'Government Scheme',
    description: 'ગુજરાત મકાન અને અન્ય બાંધકામ શ્રમયોગી કલ્યાણ બોર્ડ હેઠળ ઈ-નિર્માણ સ્માર્ટ કાર્ડ સહાય.',
    active: true,
    display_order: 3,
    required_documents: [
      { id: 'doc-enir-1', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card', doc_name_gu: 'આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-enir-2', doc_code: 'PASSBOOK', doc_name: 'Bank Passbook', doc_name_gu: 'બેંક પાસબુક', is_mandatory: true },
      { id: 'doc-enir-3', doc_code: 'RATION', doc_name: 'Ration Card', doc_name_gu: 'રેશનકાર્ડ', is_mandatory: true },
      { id: 'doc-enir-4', doc_code: 'WORK_CERT', doc_name: '90 Days Construction Certificate', doc_name_gu: '90 દિવસ કામ કર્યાનું પ્રમાણપત્ર', is_mandatory: true },
    ],
  },
  {
    id: 'srv-4',
    service_code: 'KMAM',
    name: "Kunwarbai Nu Mameru",
    name_gu: 'કુંવરબાઈનું મામેરું યોજના',
    price: 250,
    category: 'Government Scheme',
    description: 'ગુજરાત સરકારની કન્યા લગ્ન સહાય યોજના (રૂ. 12,000 સુધીની આર્થિક સહાય).',
    active: true,
    display_order: 4,
    required_documents: [
      { id: 'doc-kmam-1', doc_code: 'AADHAAR_BRIDE', doc_name: "Bride's Aadhaar", doc_name_gu: 'કન્યાનું આધાર કાર્ડ', is_mandatory: true },
      { id: 'doc-kmam-2', doc_code: 'MARRIAGE_CERT', doc_name: 'Marriage Registration Certificate', doc_name_gu: 'લગ્ન નોંધણી પ્રમાણપત્ર', is_mandatory: true },
      { id: 'doc-kmam-3', doc_code: 'INCOME_CERT', doc_name: 'Income Certificate', doc_name_gu: 'આવકનો દાખલો', is_mandatory: true },
    ],
  },
  {
    id: 'srv-5',
    service_code: 'AYUSH',
    name: 'New Ayushman Card',
    name_gu: 'નવું આયુષ્માન કાર્ડ',
    price: 150,
    category: 'Healthcare',
    description: 'પીએમ જય (PM-JAY) હેઠળ વાર્ષિક રૂ. 10 લાખ સુધીની મફત હોસ્પિટલ સારવાર માટે આયુષ્માન ભારત ગોલ્ડન કાર્ડ.',
    active: true,
    display_order: 5,
    required_documents: [
      { id: 'doc-ayush-1', doc_code: 'RATION', doc_name: 'Ration Card', doc_name_gu: 'રેશનકાર્ડ', is_mandatory: true },
      { id: 'doc-ayush-2', doc_code: 'AADHAAR', doc_name: 'Aadhaar Card with Mobile Link', doc_name_gu: 'આધાર કાર્ડ', is_mandatory: true },
    ],
  },
  {
    id: 'srv-6',
    service_code: 'AYUSHKYC',
    name: 'Ayushman Card Update / KYC',
    name_gu: 'આયુષ્માન Card Update / KYC',
    price: 50,
    category: 'Healthcare',
    description: 'આયુષ્માન કાર્ડમાં ફોટો સુધારો, બાયોમેટ્રિક ઈ-કેવાયસી અને વિગતો અપડેટ સહાય.',
    active: true,
    display_order: 6,
  },
  {
    id: 'srv-7',
    service_code: 'PMKISAN',
    name: 'PM Kisan Sahay',
    name_gu: 'PM કિસાન સહાય',
    price: 250,
    category: 'Agriculture',
    description: 'પ્રધાનમંત્રી કિસાન સન્માન નિધિ યોજના હેઠળ વાર્ષિક ₹6,000 સીધા બેંક ખાતામાં મેળવવા નવી નોંધણી.',
    active: true,
    display_order: 7,
  },
  {
    id: 'srv-8',
    service_code: 'PMKISANKYC',
    name: 'PM Kisan eKYC',
    name_gu: 'PM કિસાન KYC',
    price: 50,
    category: 'Agriculture',
    description: 'PM કિસાનના હપ્તા ચાલુ રાખવા માટે ફરજિયાત આધાર ઓટીપી અથવા બાયોમેટ્રિક e-KYC સહાય.',
    active: true,
    display_order: 8,
  },
  {
    id: 'srv-9',
    service_code: 'LANDINFO',
    name: '7/12 & 8-A Land Records PDF',
    name_gu: 'જમીનની માહિતી / PDF',
    price: 10,
    category: 'Land Records',
    description: 'AnyRoR પોર્ટલ પરથી અધિકૃત ગામ નમૂના નં. ૭/૧૨, ૮-અ અને હક્ક પત્રક નં. ૬ ની નકલ.',
    active: true,
    display_order: 9,
  },
  {
    id: 'srv-10',
    service_code: 'INCOMECERT',
    name: 'Income Certificate (આવકનો દાખલો)',
    name_gu: 'આવકનો દાખલો',
    price: 250,
    category: 'Certificates',
    description: 'મામલતદાર કચેરી / ડિજિટલ સેવા સેતુ હેઠળ માન્ય ૩ વર્ષ માટેનો આવકનો દાખલો મેળવવાની સહાય.',
    active: true,
    display_order: 10,
  },
  {
    id: 'srv-11',
    service_code: 'PFSERV',
    name: 'PF Online Services & Withdrawal',
    name_gu: 'PF Online Services',
    price: 250,
    category: 'Financial Services',
    description: 'EPFO પ્રોવિડન્ટ ફંડ ઓનલાઈન ક્લેઈમ, પૈસા ઉપાડ, KYC અને UAN એકાઉન્ટ સેવા.',
    active: true,
    display_order: 11,
  },
  {
    id: 'srv-12',
    service_code: 'IKHEDUT',
    name: 'i-Khedut Registration',
    name_gu: 'ખેડૂત નોંધણી',
    price: 150,
    category: 'Agriculture',
    description: 'i-Khedut પોર્ટલ પર કૃષિ સાધનો, દવા-ખાતર સબસિડી, તારફેન્સીંગ અને સોલાર પંપ અરજી સહાય.',
    active: true,
    display_order: 12,
  },
  {
    id: 'srv-13',
    service_code: 'MINPAN',
    name: 'Minor PAN Card (બાળકો માટે)',
    name_gu: 'Minor PAN Card',
    price: 250,
    category: 'PAN Card',
    description: '18 વર્ષથી ઓછી ઉંમરના બાળકો માટે માતા-પિતાની સહી સાથેનું પાન કાર્ડ.',
    active: true,
    display_order: 13,
  },
  {
    id: 'srv-14',
    service_code: 'VOTERNEW',
    name: 'New Voter ID Card',
    name_gu: 'નવું ચૂંટણી કાર્ડ',
    price: 150,
    category: 'Elections',
    description: 'ECI પોર્ટલ દ્વારા ફોર્મ 6 ભરીને નવું ડિજિટલ સ્માર્ટ ચૂંટણી કાર્ડ બનાવવાની સહાય.',
    active: true,
    display_order: 14,
  },
  {
    id: 'srv-15',
    service_code: 'VOTERCORR',
    name: 'Voter ID Correction',
    name_gu: 'ચૂંટણી કાર્ડ સુધારો',
    price: 150,
    category: 'Elections',
    description: 'મતદાર ઓળખપત્રમાં નામ, સરનામું, ફોટો કે જન્મ તારીખ સુધારણા (ફોર્મ 8).',
    active: true,
    display_order: 15,
  },
  {
    id: 'srv-16',
    service_code: 'ITR',
    name: 'Income Tax Return (ITR)',
    name_gu: 'Income Tax Return',
    price: 2500,
    category: 'Tax & Compliance',
    description: 'નોકરિયાત, વેપારી અને પ્રોફેશનલ્સ માટે વાર્ષિક ઇન્કમટેક્સ રિટર્ન ફાઈલિંગ સહાય.',
    active: true,
    display_order: 16,
  },
  {
    id: 'srv-17',
    service_code: 'ESHRAM',
    name: 'e-Shram Card',
    name_gu: 'ઈ-શ્રમ',
    price: 150,
    category: 'Government Scheme',
    description: 'અસંગઠિત ક્ષેત્રના શ્રમિકો માટે ભારત સરકારનું ઈ-શ્રમ રાષ્ટ્રીય સ્માર્ટ કાર્ડ.',
    active: true,
    display_order: 17,
  },
  {
    id: 'srv-18',
    service_code: 'UDYAM',
    name: 'Udyam MSME Registration',
    name_gu: 'Udyam Registration',
    price: 200,
    category: 'Business',
    description: 'નાના-મોટા ધંધા, દુકાન અને ઉદ્યોગ માટે સરકારી ઉદ્યમ રજીસ્ટ્રેશન સર્ટિફિકેટ.',
    active: true,
    display_order: 18,
  },
  {
    id: 'srv-19',
    service_code: 'POLICENOC',
    name: 'Police Verification (NOC)',
    name_gu: 'પોલીસ વેરિફિકેશન (NOC)',
    price: 150,
    category: 'Certificates',
    description: 'નોકરી, પાસપોર્ટ કે ભાડૂઆત વેરિફિકેશન માટે ગુજરાત પોલીસ ડિજિટલ NOC.',
    active: true,
    display_order: 19,
  },
  {
    id: 'srv-20',
    service_code: 'ABHA',
    name: 'ABHA Health ID Card',
    name_gu: 'ABHA Card',
    price: 150,
    category: 'Healthcare',
    description: 'આયુષ્માન ભારત ડિજિટલ મિશન હેઠળ 14 અંકનું ડિજિટલ હેલ્થ એકાઉન્ટ કાર્ડ.',
    active: true,
    display_order: 20,
  },
  {
    id: 'srv-21',
    service_code: 'PVC',
    name: 'PVC Smart Card Printing & Home Delivery',
    name_gu: 'PVC Card Printing',
    price: 150,
    category: 'Smart Cards',
    description: 'આધાર, પાન, આયુષ્માન, ચૂંટણી કાર્ડનું ઓરિજિનલ ક્વોલિટી વોટરપ્રૂફ PVC સ્માર્ટ કાર્ડ પ્રિન્ટિંગ અને હોમ ડિલિવરી.',
    active: true,
    display_order: 21,
  },
];

export const BUSINESS_KNOWLEDGE_BASE: BusinessKnowledgeItem[] = [
  {
    id: 'bk-1',
    category: 'Brand Rule',
    title: 'Business Identity & Core Purpose',
    title_gu: 'કેન્દ્રની ઓળખ અને મુખ્ય ઉદ્દેશ્ય',
    content: 'Shree Radhe Krishna Digital Service is an authorized citizen facilitation center located in Sadhli, Vadodara, Gujarat. We help rural and semi-urban citizens access official G2C digital services, identity cards, government welfare schemes, and PVC smart cards.',
    content_gu: 'શ્રી રાધે કૃષ્ણ ડિજિટલ સેવા એ સાધલી, વડોદરા સ્થિત ડિજિટલ સેવા કેન્દ્ર છે, જે નાગરિકોને સરકારી યોજનાઓ, પાન કાર્ડ, આયુષ્માન, ઈ-નિર્માણ અને PVC સ્માર્ટ કાર્ડ જેવી સેવાઓમાં અધિકૃત સહાય પૂરી પાડે છે.',
    tags: ['identity', 'location', 'purpose'],
  },
  {
    id: 'bk-2',
    category: 'Policy',
    title: 'Public Contact Policy (Email Only)',
    title_gu: 'જાહેર સંપર્ક નિયમ (માત્ર ઈમેલ)',
    content: 'As per policy, the public web portal strictly provides email support at khushidigitalseva11@gmail.com. Phone and WhatsApp interactions are handled via authorized internal CRM workflows.',
    content_gu: 'જાહેર વેબસાઇટ પર સંપર્ક માટે માત્ર ઈમેલ khushidigitalseva11@gmail.com ઉપલબ્ધ છે.',
    tags: ['contact', 'policy', 'email'],
  },
  {
    id: 'bk-3',
    category: 'Service',
    title: 'PVC Smart Card Nationwide Courier Delivery',
    title_gu: 'પીવીસી સ્માર્ટ કાર્ડ સમગ્ર ભારતમાં હોમ ડિલિવરી',
    content: 'All India PVC Smart Card home delivery is available. Cards printed with high-durability 800-micron waterproof PVC with UV overlay for Aadhaar, PAN, Voter ID, and Ayushman cards.',
    content_gu: 'સમગ્ર ભારતમાં વોટરપ્રૂફ PVC સ્માર્ટ કાર્ડ હોમ ડિલિવરી ઉપલબ્ધ છે. પાન કાર્ડ, આયુષ્માન, આધાર અને ચૂંટણી કાર્ડ માટે ઉત્તમ ગુણવત્તા.',
    price: 150,
    tags: ['pvc', 'delivery', 'cards'],
  },
  {
    id: 'bk-4',
    category: 'Legal & Disclaimer',
    title: 'Official Government Portal Compliance',
    title_gu: 'સરકારી પોર્ટલ નિયમ અને ડિસ્ક્લેમર',
    content: 'We facilitate legitimate applications on official government portals (UTIITSL, NSDL, Digital Gujarat, PM-JAY, PM-Kisan). We never bypass government portals, CAPTCHAs, or official security controls. All claims must clearly state we are a facilitation service.',
    content_gu: 'અમે સરકારી પોર્ટલ પર કાયદેસર અરજી કરવામાં સહાય કરીએ છીએ. કોઈ પણ ગેરકાયદેસર કે ભ્રામક દાવાઓ કરવામાં આવતા નથી.',
    tags: ['compliance', 'disclaimer', 'legal'],
  },
];
